# Generated by Django 3.0.6 on 2020-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200525_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='due',
            field=models.DateField(),
        ),
    ]
