# Generated by Django 3.0.6 on 2020-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200525_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='due',
            field=models.CharField(default='', max_length=8),
        ),
    ]
